### ISSUE TITLE
http://docs.debops.org/en/latest/ should corrispond to latest master of all roles.

### ISSUE THREAD

**Issue by ypid** [debops/docs#125]
I think it would make sense to setup a script, which automatically updates all submodules (maybe daily) and pushes them to the repo to build the latest docs.

**Comment by drybjed** [comment]
That would require a bot account with access to `debops/docs`, I suppose. We can run it on the webserver that hosts the wiki.

**Comment by ypid** [comment]
Here is a example myrepos config that might come in handy:

```
[repos/debops/docs]
checkout = git clone https://github.com/debops/docs.git
uppdated-submodules = git fetch && git checkout FETCH_HEAD && git submodule update --remote && git commit --all --message 'Updated all submodules to latest master.' && git push
```

**Comment by drybjed** [comment]
@ypid I'll set it up when I will have access to a Linux system. :-)

**Comment by ypid** [comment]
Nice to have: With all the [commit signing](https://github.com/debops/ansible-ifupdown/pull/48) going on I think it would be nice to also have the [debops-bot](https://github.com/debops-bot) have it’s own set of PGP keys for commit signing. @drybjed Maybe you can sign those keys to prove there integrity.

**Comment by drybjed** [comment]
I suppose that a set of GPG keys could be created for the bot, although signing will be non-interactive. How about this - let's make the bot rebuild the repository first, and then see how GPG can be added on top of that. One thing at a time. :-)

**Comment by ypid** [comment]
@drybjed Sure :-)

**Comment by ypid** [comment]
Feature has been implemented by @drybjed via the [update-submodules](https://github.com/debops/docs/blob/master/update-submodules) script which is scheduled via cron 10 minutes after every full hour.

**Comment by ypid** [comment]
debops-bot push seems not to trigger a docs build? https://github.com/debops/docs/commit/3ae5e698187604973bc4190e233c324934187cb5 should have rebuild the docs for http://docs.debops.org/en/latest/ansible/roles/ansible-bootstrap/docs/index.html I guess.

**Comment by ypid** [comment]
Never mind. I seem to confused the changelog of `debops.bootstrap` with that of another role.

**Comment by drybjed** [comment]
Yeah, it looks like bot works fine at the moment.
