### ISSUE TITLE
hosts file syntax

### ISSUE THREAD

**Issue by roman-io** [debops/docs#24]
Seems like syntax is not supported:
http://docs.debops.org/en/latest/getting-started.html
```
[all my servers]
server1   hostname=serverone.example.com
```

http://docs.ansible.com/intro_inventory.html
This will work, and maybe better to avoid spaces in group name
```
[all_my_servers]
server1   ansible_ssh_host=serverone.example.com
```

Edit Continuing with the 'Getting started':
debops -vvvv -u root --ask-pass

```
PLAY [Prepare base environment] *********************************************** 

TASK: [Create root directories] *********************************************** 
fatal: [server1] => template error while templating string: no filter named 'map'

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
Check IP address of Ansible Controller ---------------------------------- 0.02s
Create root directories ------------------------------------------------- 0.02s
           to retry, use: --limit @/home/roman/site.retry

server1                    : ok=2    changed=0    unreachable=1    failed=0   
```
Also 'ssh_host_allow: [ '192.168.178.0/24' ]' ssh_host_allow is not described anywhere in the docs.

**Comment by drybjed** [comment]
@roman-io Thanks for the bug report! I will update the docs shortly.

**Comment by drybjed** [comment]
@roman-io I'm sorry, I think I missed your problem there... You need to update Jinja package on your Ansible Controller to a newer version which supports `map()` filter.
