### ISSUE TITLE
Links to role docs broken

### ISSUE THREAD

**Issue by patrickvale** [debops/docs#289]
Looking at the docs for master, for example at [this point](https://docs.debops.org/en/master/introduction/getting-started.html#sshd-whitelist) of 'Getting Started', the link to the [debops.sshd role](https://docs.debops.org/en/master/ansible/roles/debops.sshd/index.html#debops-sshd) goes to a page not found.

The same seems to happen for all the roles.

Digging into the history, the latest 'available' version of the role docs seems to be 1.1 - do, for instance, I can get to the debops.sshd role docs at [https://docs.debops.org/en/stable-1.1/ansible/roles/debops.sshd/index.html](https://docs.debops.org/en/stable-1.1/ansible/roles/debops.sshd/index.html)

**Comment by drybjed** [comment]
Looks like something happened on the ReadTheDocs website which is hosting the DebOps documentation. I'm not sure yet what, I reached out to the RTD team on IRC, currently awaiting response.

**Comment by drybjed** [comment]
The documentation was fixed with the help of the RTD team, it should work fine now.
