### ISSUE TITLE
'Edit on GitHub' links 404

### ISSUE THREAD

**Issue by davisonio** [debops/docs#91]
When using the button on any page which is included into the docs via a submodule produces a 404 error.

**Comment by drybjed** [comment]
DebOps uses ReadTheDocs template by default. Is there a way to change the "Edit on GitHub" link via some template string?

**Comment by ypid** [comment]
@drybjed Noted that the button on the left which needs to be expanded first still redirects to the wrong target. Currently, only the big "Edit on GitHub" at the top right of the page works. It is left to the reader to figure out how to fix the bottom one :stuck_out_tongue:
